language: go

go:
- 1.x
- 1.12.x
- master

script:
 -go build
 -go run

deploy:
  provider: heroku
  api_key:
    secure: hcJVfkOWSLq+DcJkU6IH6HgAOZGleEJ/08LlQQyg/AcvdEwFke1l5GrBtLWSnLSgJwEIe7prOKQMN94OfIJ21S3VtyQwgOXpKJCXskOP+uWzxX2eOZdmWHJ/mGYgohQVFEPE8YD+t1+KaMVwxNaB5afc7K68juqd8xicZo8ygWDPI/+QGukiFioGKHOiioT2rdooS6P4Xtdca/rJWshjwgzZG0jN3UqQBCJmvxCju8PL9dgu45ytD0Y3blxyQScVKOD9gk8nY07sYuGNoqcBQ8vSTSiKRUuwrR5gX1F6a8vFN1MDzMW0dnYdo/i06SOw/hnmaABGf5Iv6rjvCkdvJRn9woT6NQfHOaqHVWugacpCMWodVqBYIjimHAqn+z3sEAlp0GKCkD4n2vpJRtjk/kegNLcGOnHsURGLXiYy/4qTjw9RhqameeBV3F4m1E8nmflIu6xlaQQu8+lQ2izYkRV+T0tlfa/GP02V4BUBgmWstGPh5jLJ421LFhKebFOPKataa+GXG55eoaGieQIM9BY5nlOicir0tE8aSyne1uYaoyOHUjhn1zbY233OrCd24JgW/mJp1/n4Ud6OGh96gCNBftG7b/bPMLGjYwz80BfrD+nJX9NkWbp6C+qYPOckwdbnIjDGua4jJdidyRtxnIvW+MU5CCkOF6Plcn5F3Gk=
  app: ilovephysics
  on:
    repo: maverick-tech/ilovephysics.com
