language: go
deploy:
  provider: heroku
  api_key:
    secure: r+IthrwsWSnd9Ll4S8vVi6GWzwTfCU2yz2dEPks5FBPnGZBaU53Er4UyHQSB7R4c3deMS+1482sbSpQUAC+gWu7mbUU82vHzBFMRL++qNkaX/kZiFQg3ESVlCosPs9/FJqfm2xNZNM/j26lAPULfLBwBNC7ewldrFjcrZE9pn4c2qCa53XhNkRjRUYTwD0RABnD75ku+1JvQZLZAI4Kc+2bdHTROFOWxIK6954go1Y6c98ziJwYqyomRrDnf3vDvDn7ut0lZLX3iIqAclPkO6IK9B6mtocjdXwVQnVZXxw2FVe6Khud2y7AlFt0LLMt6CTS87etk24Vbqu9Dz9vGB/biknQD6JaWyyiJdvTQ7pgyE76qtUADrBpLtU79uPRcdH/XPMYZrI88giHkJmHYa74/jpbvO81QKTSm4vG5k67RRawfrEqDvWfqAZNb1x+QM/HXAgLEKhIdmLWsLxkeahF1uKwhxXEnQzjAOjwlkX1QUj3rzTmddT+tZOTGWRKfatEPi4bOgaiFA/e3Vfg+y2DvgePSm6BksnpOdyBSIv2xS9TSyforrNjqqGeKe3b/O3mkyU6c2h8Gqyh80j2FWOLke4tN42P9G8sEquAA4oo66T/9pY15YHf29DQFjJRqab0ND6fe4/RP+cKLOku5jkdMf9sYNMEAIQGIQol2h+I=
  app: ilovephysics.com
  on:
    repo: maverick-tech/ilovephysics.com
